#pragma once

typedef enum {
    KEYSTORE_ERROR_OK,
    KEYSTORE_ERROR_MEM,
    KEYSTORE_ERROR_INVALID,
    KEYSTORE_ERROR_VERSION,
    KEYSTORE_ERROR_FILE_EXISTS,
    KEYSTORE_ERROR_INIT,
    KEYSTORE_ERROR_OPEN,
    KEYSTORE_ERROR_READ,
    KEYSTORE_ERROR_WRITE,
    KEYSTORE_ERROR_PW_SALT_DATA,
    KEYSTORE_ERROR_PW_SALT,
    KEYSTORE_ERROR_PW,
    KEYSTORE_ERROR_LEN,
    KEYSTORE_ERROR_EMPTY,
    KEYSTORE_ERROR_TYPE,
    KEYSTORE_ERROR_NOT_FOUND
} keystore_error_t;
