#pragma once

typedef enum {
    KEYSTORE_ERROR_OK,
    KEYSTORE_ERROR_MEM,
    KEYSTORE_ERROR_NO_FILE,
    KEYSTORE_ERROR_NOT_KS,
    KEYSTORE_ERROR_VERSION,
    KEYSTORE_ERROR_FILE_EXISTS,
    KEYSTORE_ERROR_IO_OPEN,
    KEYSTORE_ERROR_IO_READ,
    KEYSTORE_ERROR_IO_WRITE,
    KEYSTORE_ERROR_LEN,
    KEYSTORE_ERROR_PW_SALT_DATA,
    KEYSTORE_ERROR_PW_SALT,
    KEYSTORE_ERROR_PW,
    KEYSTORE_ERROR_PW_INVALID
} keystore_error_t;
